using System.Globalization;
using System.Reflection;
using System.Resources;

namespace SciFiEditor.App.Resources;

public static class Strings
{
    private static readonly ResourceManager ResourceManager =
        new("SciFiEditor.App.Resources.Strings", Assembly.GetExecutingAssembly());

    public static string MenuFile => Get("MenuFile");
    public static string MenuEdit => Get("MenuEdit");
    public static string MenuView => Get("MenuView");
    public static string MenuProject => Get("MenuProject");
    public static string MenuHelp => Get("MenuHelp");
    public static string TabText => Get("TabText");
    public static string TabBoard => Get("TabBoard");
    public static string TabPreview => Get("TabPreview");
    public static string InspectorSynopsis => Get("InspectorSynopsis");
    public static string InspectorNotes => Get("InspectorNotes");
    public static string StatusReady => Get("StatusReady");
    public static string MenuNewProject => Get("MenuNewProject");
    public static string MenuOpenProject => Get("MenuOpenProject");
    public static string MenuRecentProjects => Get("MenuRecentProjects");
    public static string MenuSave => Get("MenuSave");
    public static string BinderAddFolder => Get("BinderAddFolder");
    public static string BinderAddChapter => Get("BinderAddChapter");
    public static string BinderAddScene => Get("BinderAddScene");
    public static string BinderRename => Get("BinderRename");
    public static string BinderDuplicate => Get("BinderDuplicate");
    public static string BinderMoveToTrash => Get("BinderMoveToTrash");
    public static string BinderTrashTitle => Get("BinderTrashTitle");
    public static string DialogNewProjectTitle => Get("DialogNewProjectTitle");
    public static string DialogNewProjectName => Get("DialogNewProjectName");
    public static string DialogNewProjectLocation => Get("DialogNewProjectLocation");
    public static string DialogBrowse => Get("DialogBrowse");
    public static string DialogOk => Get("DialogOk");
    public static string DialogCancel => Get("DialogCancel");
    public static string ErrorTitle => Get("ErrorTitle");
    public static string BinderNewFolderTitle => Get("BinderNewFolderTitle");
    public static string BinderNewChapterTitle => Get("BinderNewChapterTitle");
    public static string BinderNewSceneTitle => Get("BinderNewSceneTitle");
    public static string InspectorLabel => Get("InspectorLabel");
    public static string InspectorStatus => Get("InspectorStatus");
    public static string InspectorTargetWordCount => Get("InspectorTargetWordCount");
    public static string StatusNone => Get("StatusNone");
    public static string StatusDraft => Get("StatusDraft");
    public static string StatusRevised => Get("StatusRevised");
    public static string StatusFinal => Get("StatusFinal");
    public static string StatusBarSceneWords => Get("StatusBarSceneWords");
    public static string StatusBarProjectWords => Get("StatusBarProjectWords");
    public static string StatusBarSessionDelta => Get("StatusBarSessionDelta");
    public static string MenuStatistics => Get("MenuStatistics");
    public static string StatsWindowTitle => Get("StatsWindowTitle");
    public static string StatsHeatmapLabel => Get("StatsHeatmapLabel");
    public static string StatsChartLabel => Get("StatsChartLabel");
    public static string StatsStreakLabel => Get("StatsStreakLabel");
    public static string StatsDailyGoalLabel => Get("StatsDailyGoalLabel");
    public static string StatsSessionGoalLabel => Get("StatsSessionGoalLabel");
    public static string StatsSaveGoals => Get("StatsSaveGoals");
    public static string MenuCompile => Get("MenuCompile");
    public static string BinderIncludeInCompile => Get("BinderIncludeInCompile");
    public static string CompileWindowTitle => Get("CompileWindowTitle");
    public static string CompileFormatLabel => Get("CompileFormatLabel");
    public static string CompileExportButton => Get("CompileExportButton");
    public static string CompileSuccess => Get("CompileSuccess");
    public static string BinderSnapshots => Get("BinderSnapshots");
    public static string SnapshotsWindowTitle => Get("SnapshotsWindowTitle");
    public static string SnapshotTakeButton => Get("SnapshotTakeButton");
    public static string SnapshotRestoreButton => Get("SnapshotRestoreButton");
    public static string SnapshotRestoreConfirm => Get("SnapshotRestoreConfirm");
    public static string SnapshotTaken => Get("SnapshotTaken");
    public static string SnapshotRestored => Get("SnapshotRestored");
    public static string MenuEntities => Get("MenuEntities");
    public static string EntityWindowTitle => Get("EntityWindowTitle");
    public static string EntityTabCharacters => Get("EntityTabCharacters");
    public static string EntityTabLocations => Get("EntityTabLocations");
    public static string EntityAddButton => Get("EntityAddButton");
    public static string EntityDeleteButton => Get("EntityDeleteButton");
    public static string MenuSearch => Get("MenuSearch");
    public static string SearchWindowTitle => Get("SearchWindowTitle");
    public static string SearchButton => Get("SearchButton");
    public static string FindNext => Get("FindNext");
    public static string FindPrevious => Get("FindPrevious");
    public static string ReplaceOne => Get("ReplaceOne");
    public static string ReplaceAll => Get("ReplaceAll");
    public static string MenuFocusMode => Get("MenuFocusMode");
    public static string MenuToggleTheme => Get("MenuToggleTheme");
    public static string MenuUndo => Get("MenuUndo");
    public static string MenuRedo => Get("MenuRedo");
    public static string MenuCut => Get("MenuCut");
    public static string MenuCopy => Get("MenuCopy");
    public static string MenuPaste => Get("MenuPaste");
    public static string MenuSelectAll => Get("MenuSelectAll");
    public static string MenuFind => Get("MenuFind");
    public static string SeedSceneContent => Get("SeedSceneContent");
    public static string StartupTitle => Get("StartupTitle");
    public static string StartupSubtitle => Get("StartupSubtitle");
    public static string StartupNewProject => Get("StartupNewProject");
    public static string StartupOpenProject => Get("StartupOpenProject");
    public static string StartupContinueWithoutProject => Get("StartupContinueWithoutProject");
    public static string StartupRecentProjectsLabel => Get("StartupRecentProjectsLabel");
    public static string StartupNoRecentProjects => Get("StartupNoRecentProjects");
    public static string FormatHeadingNormal => Get("FormatHeadingNormal");
    public static string FormatBulletList => Get("FormatBulletList");
    public static string FormatNumberedList => Get("FormatNumberedList");
    public static string FormatBold => Get("FormatBold");
    public static string FormatItalic => Get("FormatItalic");
    public static string FormatStrikethrough => Get("FormatStrikethrough");
    public static string FormatLink => Get("FormatLink");
    public static string FormatMore => Get("FormatMore");
    public static string FormatBlockquote => Get("FormatBlockquote");
    public static string FormatCode => Get("FormatCode");
    public static string FormatHorizontalRule => Get("FormatHorizontalRule");
    public static string DialogLinkUrl => Get("DialogLinkUrl");
    public static string DialogLinkText => Get("DialogLinkText");
    public static string DialogInsertLinkTitle => Get("DialogInsertLinkTitle");

    private static string Get(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;
}
